config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"

  namespace :api, defaults: {format: :json} do
    get 'products/distinct_categories' => 'products#distinct_categories'
    resources :products, except: [:edit, :new]
    post 'products/mass_user_prices'
    post 'products/mass_product_data'
    get 'products/:id/historical_prices' => 'products#historical_prices'
    resources :companies, except: [:edit, :new]
    resource :user_percents, only: [:show, :create]
  end 

  resources :users, only: [:update, :create, :edit, :new]
  resource :session, only: [:create, :new, :destroy]
  resource :email, defaults: {format: :json}, only: []
  post 'email/send_to_all' => 'email#send_to_all'
  post 'email/send_to_self' => 'email#send_to_self'
  post 'email/resend_activation_email' => 'email#resend_activation_email'
  resource :excel, only: []
  post 'excel/import_products' => 'excel#import_products'
  post 'excel/upload_user_prices' => 'excel#upload_user_prices'
  post 'excel/import_company_prices' => 'excel#import_company_prices'
  get 'excel/export_user_uploads' => 'excel#export_user_uploads'
  get 'excel/export_user_data' => 'excel#export_user_data' 

  get 'excel/seeded_products' => 'excel#seeded_products' 
  get 'excel/seeded_user_uploads' => 'excel#seeded_user_uploads' 
  get 'excel/seeded_price_uploads' => 'excel#seeded_price_uploads'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/views/layouts/application.html.erb
<!DO/quasimonomial/pricepda/commits/allCTYPE html>
<html>
<head>
  <title>Pricepda</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>


</head>
<body>
	<div class="top_nav">
        
        <div class="container">
            <div class="row-fluid">
                <div class="span7">
                                    </div>
                <div class="span3">
                                    </div>
                <div class="span2">
                                    </div>
            </div>
        </div>
    </div>

    <header id="header">
        <div class="container">
    	   <div class="row-fluid">
                <div class="span12">

                <!-- Logo -->
		                              
                <div id="logo" class="">
                </div><!-- #logo -->
            
                </div>
            </div>

        </div>

    </header>

    <div class="top_wrapper">

    <!-- .header -->        

    
        
        <!-- Page Head -->
    
    <div class="header_page">
            <div class="container">
            <h2>Online Price Comparison Tool</h2>  <span class="subtitle"><span>/</span></span>
            </div>
            
    </div> 

    <div class="header_shadow"></div> 

	</div>

    <div style="padding:30px">
	<% if logged_in? %>
		<% if current_user.is_admin %>
			<p>You are an admin!</p>
		<% end %>
		<% unless current_user.activated %>
			<p>Your account is not activated!  Please check your email and activate your account.</p>
		<% end %>

		<%= link_to "Edit your settings", edit_user_url(current_user) %>
		<%= button_to "Sign Out", session_url, :method => :delete %>
	<% else %>
		<%= link_to "Sign In", new_session_url %>
		<%= link_to "Sign Up", new_user_url %>
	<% end %>
	
	<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>
	<%= flash[:info].html_safe if flash[:info] %>
	<%= yield %>
    </div>

	<div class="footer_wrapper">
        <div class="top_footer"><div class="container"><ul class='tweet_list' id='tweet_footer'><li></li></ul><div class="pagination pull-right"><a href="#" class="back"><i class="icon-arrow-left"></i></a><a href="#" class="next"><i class="icon-arrow-right"></i></a>  </div><span class="shadow_top_footer"></span></div>
    </div>
       <footer id="footer">
        
         	<div class="inner">
	    	<div class="container">
	        	<div class="row-fluid ff">
                
                <!-- widget -->
	            <div class="span6"></div>
                <div class="span6"></div>                            
	            </div>
	        </div>
        </div>
                <div id="copyright">
	    	<div class="container">
	        	<div class="row">
		        	
                </div>
            </div>
        </div><!-- #copyright -->

    	</footer>

</body>
</html>